/**
 * Pure logic for the patterns-index generator/validator.
 *
 * `.agent/memory/active/patterns/README.md` carries a "Pattern Index" section
 * listing every pattern grouped by category. That index is a *derived*
 * artefact: hand-maintaining it guarantees drift (a real estate's hand-kept
 * index listed 87 of 132 files on disk). These helpers recompute the index
 * from each pattern file's frontmatter so the README index is generated, not
 * hoped — the `readme-as-index` / `governance-claim-needs-a-scanner` doctrine
 * made mechanical, and the honest anti-drift form (recompute-and-compare, never
 * a hand-edited literal).
 *
 * Repo-agnostic by construction: nothing here names a repository, so the same
 * code regenerates any Practice estate's pattern index.
 *
 * @packageDocumentation
 */

import { parse as parseYaml } from 'yaml';

/** Sentinel marking the start of the generated index region in the README. */
export const PATTERN_INDEX_START =
  '<!-- PATTERN-INDEX:START (generated by validate-patterns-index; do not edit this region by hand) -->';

/** Sentinel marking the end of the generated index region in the README. */
export const PATTERN_INDEX_END = '<!-- PATTERN-INDEX:END -->';

/**
 * Canonical category order, per the patterns README taxonomy. Categories are
 * rendered in this order; any category value outside this list renders after
 * these (alphabetically) and is a gate-failing conformance error.
 */
const CANONICAL_CATEGORIES = ['code', 'architecture', 'process', 'testing', 'agent'] as const;

/** Canonical polarity values; anything else is a gate-failing conformance error. */
const CANONICAL_POLARITIES = ['pattern', 'anti-pattern'] as const;

/** A single pattern, distilled from one pattern file's frontmatter. */
export interface PatternEntry {
  /** Pattern file basename, e.g. `additive-only-schema-decoration.md`. */
  readonly file: string;
  /** Human-readable name from frontmatter `name`. */
  readonly name: string;
  /** Lower-cased `category` value (raw — not normalised to the canonical set). */
  readonly category: string;
  /** `polarity` value, or empty string when absent. */
  readonly polarity: string;
  /** `use_this_when` discovery sentence, or empty string when absent. */
  readonly useThisWhen: string;
}

/** Outcome of parsing one pattern file. */
export interface ParsedPatternFile {
  /** The parsed entry, or `null` when the frontmatter was unparseable. */
  readonly entry: PatternEntry | null;
  /**
   * Gate-failing problems with this file: unparseable frontmatter or any
   * frontmatter-schema violation (missing `name` / `use_this_when`,
   * non-canonical `category` / `polarity`). Conformance is strict — every
   * pattern must declare a `name`, a canonical `polarity`, a canonical
   * `category`, and a `use_this_when`.
   */
  readonly errors: readonly string[];
}

function asString(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

/**
 * Parse one pattern file's frontmatter into a {@link PatternEntry}.
 *
 * Any schema violation is a gate-failing error (strict conformance). A
 * deterministic fallback still populates the returned entry so the index stays
 * renderable for diagnostics, but the errors fail the run until the source is
 * fixed.
 *
 * @param file    - The pattern file basename (used in messages and the link).
 * @param content - Full text of the pattern file.
 */
export function parsePatternFile(file: string, content: string): ParsedPatternFile {
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(content);
  if (!match) {
    return { entry: null, errors: [`${file}: missing YAML frontmatter block`] };
  }
  let data: unknown;
  try {
    data = parseYaml(match[1]);
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : 'unknown YAML error';
    return { entry: null, errors: [`${file}: invalid YAML frontmatter — ${message}`] };
  }
  const record = (data && typeof data === 'object' ? data : {}) as Record<string, unknown>;
  const errors: string[] = [];

  let name = asString(record['name']);
  if (!name) {
    name = file.replace(/\.md$/, '');
    errors.push(`${file}: missing 'name' frontmatter`);
  }

  let category = asString(record['category']).toLowerCase();
  if (!category) {
    category = 'uncategorised';
    errors.push(`${file}: missing 'category' frontmatter`);
  } else if (!(CANONICAL_CATEGORIES as readonly string[]).includes(category)) {
    errors.push(
      `${file}: non-canonical category '${category}' (canonical: ${CANONICAL_CATEGORIES.join(', ')})`,
    );
  }

  const polarity = asString(record['polarity']);
  if (!polarity) {
    errors.push(`${file}: missing 'polarity' frontmatter`);
  } else if (!(CANONICAL_POLARITIES as readonly string[]).includes(polarity)) {
    errors.push(
      `${file}: non-canonical polarity '${polarity}' (canonical: ${CANONICAL_POLARITIES.join(', ')})`,
    );
  }

  const useThisWhen = asString(record['use_this_when']);
  if (!useThisWhen) {
    errors.push(`${file}: missing 'use_this_when' frontmatter`);
  }

  return { entry: { file, name, category, polarity, useThisWhen }, errors };
}

/** A category section of the rendered index. */
export interface PatternIndexGroup {
  /** Raw category key. */
  readonly category: string;
  /** Display title (title-cased category). */
  readonly title: string;
  /** Entries in this category, sorted by name. */
  readonly entries: readonly PatternEntry[];
}

function titleCase(category: string): string {
  return category
    .split('-')
    .map((word) => (word ? word[0].toUpperCase() + word.slice(1) : word))
    .join(' ');
}

function categoryRank(category: string): number {
  const index = (CANONICAL_CATEGORIES as readonly string[]).indexOf(category);
  return index === -1 ? CANONICAL_CATEGORIES.length : index;
}

/**
 * Group entries by category in canonical-then-alphabetical order; within each
 * group, entries are sorted by name (case-insensitive).
 */
export function groupPatternEntries(entries: readonly PatternEntry[]): PatternIndexGroup[] {
  const byCategory = new Map<string, PatternEntry[]>();
  for (const entry of entries) {
    const list = byCategory.get(entry.category) ?? [];
    list.push(entry);
    byCategory.set(entry.category, list);
  }
  return [...byCategory.keys()]
    .sort((a, b) => categoryRank(a) - categoryRank(b) || a.localeCompare(b))
    .map((category) => ({
      category,
      title: titleCase(category),
      entries: [...(byCategory.get(category) ?? [])].sort((a, b) =>
        a.name.localeCompare(b.name, 'en', { sensitivity: 'base' }),
      ),
    }));
}

function renderEntry(entry: PatternEntry): string {
  const link = `[${entry.file}](${entry.file})`;
  const discovery = entry.useThisWhen ? ` -- Use this when: ${entry.useThisWhen}` : '';
  return `- **${entry.name}**${discovery} → ${link}`;
}

/**
 * Render the index body — the markdown between the sentinels: one
 * `### Category (N)` section per category. The `## Pattern Index` heading and
 * the "this is generated" note are stable README text *outside* the sentinels,
 * so only the volatile sections are regenerated. Deterministic and
 * prettier-stable (the repo uses prettier defaults, so `proseWrap` is
 * "preserve" and long lines are not rewrapped).
 */
export function renderPatternIndexBody(groups: readonly PatternIndexGroup[]): string {
  return groups
    .map((group) => {
      const lines = group.entries.map(renderEntry).join('\n');
      return `### ${group.title} (${group.entries.length})\n\n${lines}`;
    })
    .join('\n\n');
}

/** Outcome of {@link replaceIndexRegion}. */
export interface RegionReplaceResult {
  /** Whether the sentinels were found and the region replaced. */
  readonly ok: boolean;
  /** The resulting README text (unchanged from the input when `ok` is false). */
  readonly next: string;
  /** Error message when the sentinels are absent, else `null`. */
  readonly error: string | null;
}

/**
 * Replace the sentinel-delimited index region in a README with `body`,
 * preserving everything outside the region. Fails when either sentinel is
 * absent (the README has not been prepared for generation). Idempotent: a
 * second call with the same `body` produces identical output.
 */
export function replaceIndexRegion(readme: string, body: string): RegionReplaceResult {
  const startAt = readme.indexOf(PATTERN_INDEX_START);
  const endAt = readme.indexOf(PATTERN_INDEX_END);
  if (startAt === -1 || endAt === -1 || endAt < startAt) {
    return {
      ok: false,
      next: readme,
      error: `missing the ${PATTERN_INDEX_START} / ${PATTERN_INDEX_END} sentinels`,
    };
  }
  const before = readme.slice(0, startAt);
  const after = readme.slice(endAt + PATTERN_INDEX_END.length);
  const region = `${PATTERN_INDEX_START}\n\n${body}\n\n${PATTERN_INDEX_END}`;
  return { ok: true, next: `${before}${region}${after}`, error: null };
}
